### ISSUE TITLE
Implementation of Kernel#yield_self (ruby 2.5.0)

### ISSUE THREAD

**Issue by tinchi** [graalvm/truffleruby#142]
Hi 

So where should I start?

**Comment by chrisseaton** [comment]
Welcome to TruffleRuby!

The first thing you need to do is to write some specs for it. They have a single test in MRI, but we'd generally prefer to use specs because we find these easier to work with and we can include them without merging all of MRI's trunk tests.

See if you can create some specs for `Kernel#yield_self` to start with, testing against MRI and making sure they pass there. Copy something like `Object#tap` to get started.

**Comment by chrisseaton** [comment]
Sorry I probably spoke too soon here. It seems like the feature is still under active discussion.

https://bugs.ruby-lang.org/issues/13559

We should probably wait out on this until it's all settled. I can suggest other features that we need if you still want to contribute.

**Comment by tinchi** [comment]
sure, which one you have in mind?

Am 17.05.2017 18:50 schrieb "Chris Seaton" <notifications@github.com>:

**Comment by chrisseaton** [comment]
It's not as fun as new feature from scratch, but we still have many tagged failing specs for the core library. Some of them are entirely missing methods, but most are minor edge cases. Working on these would be extremely helpful.

https://github.com/graalvm/truffleruby/tree/master/spec/tags/core

Here's how to tackle them:

https://github.com/graalvm/truffleruby/blob/4f2dab7c235c416ab7bdec286234778d6dc38548/doc/contributor/workflow.md#how-to-fix-a-failing-spec

These ones might be easy enough to get started on.

https://github.com/graalvm/truffleruby/blob/4f2dab7c235c416ab7bdec286234778d6dc38548/spec/tags/core/kernel/rand_tags.txt
