### ISSUE TITLE
slow json encoding

### ISSUE THREAD

**Issue by prdn** [graalvm/truffleruby#146]
Hello

I tested with v0.21 (0.22 gives some gem trouble) this small example as a starter code to integrate with `benchmark/ips`
Problem is that even the code above takes around 21 minutes (`Time.now - t1`) to run, where MRI takes only 50 seconds.

```
require 'json'

cnt = 0

while true
  JSON.dump({ :test => 1 })
  cnt = cnt + 1
  break if cnt > 1000000
end

cnt = 0

t1 = Time.now
while true
  JSON.dump({ :test => 1 })
  cnt = cnt + 1
  break if cnt > 10000000
end

puts (Time.now - t1) * 1000
```

Anything you need to optimise still?

Thanks for all your effort

**Comment by chrisseaton** [comment]
Hi, thanks for the report. Yes JSON parsing and encoding is really slow at the moment. I think it hits some weaknesses in how we implement strings. We're also running the pure Ruby version, rather than the C extension or Java version that MRI, JRuby and I believe Rubinius use. @nirvdrum can you remember what it was in particular? It's probably time to start trying to address this.

**Comment by nirvdrum** [comment]
We only have a pure Ruby version of the `json` gem and IIRC, it makes extensive use of regexps, which we haven't spent much time on optimizing.

**Comment by prdn** [comment]
Thanks for replying and your amazing work.
I really look forward in being able to use truffle in production.

**Comment by bjfish** [comment]
I tried running the example from the description in `TruffleRuby master (w/ Graal)` vs `MRI 2.3.4` and saw `55,403.1` for MRI and `10,112.0` for TruffleRuby. So, it looks like about a 5x speedup on this example over MRI right now.

**Comment by prdn** [comment]
Yes, indeed much better now :+1: 
I think we can close the issue.
Would be amazing to see `Oj` supported by Truffle as soon as C support is complete.
