### ISSUE TITLE
Is there a performance difference between SVM and JVM?

### ISSUE THREAD

**Issue by ipepe** [graalvm/truffleruby#260]
Is there a performance difference between SVM and JVM? I'm not asking about startup. I'm asking about computational performance after startup. Is there a preferred way to run TruffleRuby?

**Comment by eregon** [comment]
Hello,

It should be very similar, because Just-in-Time compilation as done by Graal is performed in both cases.
However, SVM is a different VM and might have different trade-offs, GCs, and optimizations than HotSpot.
Currently, TruffleRuby on SVM is less mature/tested than TruffleRuby on JVM, but this will improve over time, bugs are being fixed.
So for now we recommend using TruffleRuby on JVM for best peak performance, but feel free to try SVM for a faster startup.

**Comment by chrisseaton** [comment]
I'm closing this issue as I think the question is answered. Please feel free to re-open if it isn't.
