### ISSUE TITLE
Question about to try TruffleRuby

### ISSUE THREAD

**Issue by Fudoshiki** [graalvm/truffleruby#91]
Hello, this can be newbie question, but i can't find how to try master branch truffleruby from git

my steps
- download `GraalVM preview for Mac OS X (0.20), with Labs JDK` 8 from http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html
- extract
- download master branch archive
- extract in folder with graalvm

Is this right way?

**Comment by chrisseaton** [comment]
The master branch of TruffleRuby isn't always compatible with GraalVM, as APIs change. We recommend people who want to build TruffleRuby from scratch [build graalVM from source](https://github.com/graalvm/truffleruby/blob/master/doc/contributor/building-graal.md).

Does that allow you to do what you want? Or did you have some complex requirement where you really want to use GraaLVM?

**Comment by Fudoshiki** [comment]
I want to try in real application like rails

**Comment by pitr-ch** [comment]
Ruby is also part of the GraalVM itself. Using TruffleRuby from a repo is recommended only when you need newer version than the version of TruffleRuby included in GraalVM or for contributing to TruffleRuby. Latest version of TruffleRuby should be out in GraaVM 0.21 in few days. Ruby from GraalVM 0.21 only has to be added to a Ruby manager before use. No compilation needed.

Correct version might be already included in GraalVM depending on which version you've downloaded. Otherwise the link you've posted is ok or the Java8 from Oracle OTN will work too.

**Comment by chrisseaton** [comment]
Yes, for your use case you should use the version of Ruby included with GraalVM.

https://github.com/graalvm/truffleruby/blob/e4c6d7166846cb6fd1701eb737968112de017958/doc/user/using-graalvm.md

I'll close this issue, as that's the answer to that question. If you have more questions about setting up and getting running we can answer them in real time if you catch us in Gitter here

https://gitter.im/graalvm/truffleruby
